- name: Action Lint
  # You may pin to the exact commit or the version.
  # uses: panda0603/lint-action@96fafdf5a95139ecf44ede90b32fd92d79f59a7f
  uses: panda0603/lint-action@1.6.3
  with:
    # The GITHUB_TOKEN secret
    github_token: 
    # Whether linters should try to fix code style issues automatically
    auto_fix: # optional
    # Username for auto-fix commits
    git_name: # optional, default is Lint Action
    # Email address for auto-fix commits
    git_email: # optional, default is lint-action@samuelmeuli.com
    # Template for auto-fix commit messages. The "${linter}" variable can be used to insert the name of the linter which has created the auto-fix
    commit_message: # optional, default is Fix code style issues with ${linter}
    # Template for the name of the check run. The "${linter}" and "${dir}" variables can be used to insert the name and directory of the linter.
    check_name: # optional, default is ${linter}
    # Enable or disable stylelint checks
    stylelint: # optional
    # Additional arguments to pass to the linter
    stylelint_args: # optional, default is 
    # Directory where the stylelint command should be run
    stylelint_dir: # optional
    # Extensions of files to check with stylelint
    stylelint_extensions: # optional, default is css,sass,scss
    # Shell command to prepend to the linter command
    stylelint_command_prefix: # optional, default is 
    # Enable or disable gofmt checks
    gofmt: # optional
    # Additional arguments to pass to the linter
    gofmt_args: # optional, default is 
    # Directory where the gofmt command should be run
    gofmt_dir: # optional
    # Extensions of files to check with gofmt
    gofmt_extensions: # optional, default is go
    # Shell command to prepend to the linter command
    gofmt_command_prefix: # optional, default is 
    # Enable or disable golint checks
    golint: # optional
    # Additional arguments to pass to the linter
    golint_args: # optional, default is 
    # Directory where the golint command should be run
    golint_dir: # optional
    # Extensions of files to check with golint
    golint_extensions: # optional, default is go
    # Shell command to prepend to the linter command
    golint_command_prefix: # optional, default is 
    # Enable or disable ESLint checks
    eslint: # optional
    # Additional arguments to pass to the linter
    eslint_args: # optional, default is 
    # Directory where the ESLint command should be run
    eslint_dir: # optional
    # Extensions of files to check with ESLint
    eslint_extensions: # optional, default is js
    # Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    eslint_command_prefix: # optional, default is 
    # Enable or disable Prettier checks
    prettier: # optional
    # Additional arguments to pass to the linter
    prettier_args: # optional, default is 
    # Directory where the Prettier command should be run
    prettier_dir: # optional
    # Extensions of files to check with Prettier
    prettier_extensions: # optional, default is css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml
    # Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    prettier_command_prefix: # optional, default is 
    # Enable or disable XO checks
    xo: # optional
    # Additional arguments to pass to the linter
    xo_args: # optional, default is 
    # Directory where the XO command should be run
    xo_dir: # optional
    # Extensions of files to check with XO
    xo_extensions: # optional, default is js
    # Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    xo_command_prefix: # optional, default is 
    # Enable or disable PHP_CodeSniffer checks
    php_codesniffer: # optional
    # Additional arguments to pass to the linter
    php_codesniffer_args: # optional, default is 
    # Directory where the PHP_CodeSniffer command should be run
    php_codesniffer_dir: # optional
    # Extensions of files to check with PHP_CodeSniffer
    php_codesniffer_extensions: # optional, default is php
    # Shell command to prepend to the linter command
    php_codesniffer_command_prefix: # optional, default is 
    # Enable or disable Black checks
    black: # optional
    # Additional arguments to pass to the linter
    black_args: # optional, default is 
    # Directory where the Black command should be run
    black_dir: # optional
    # Extensions of files to check with Black
    black_extensions: # optional, default is py
    # Shell command to prepend to the linter command
    black_command_prefix: # optional, default is 
    # Enable or disable Flake8 checks
    flake8: # optional
    # Additional arguments to pass to the linter
    flake8_args: # optional, default is 
    # Directory where the Flake8 command should be run
    flake8_dir: # optional
    # Extensions of files to check with Flake8
    flake8_extensions: # optional, default is py
    # Shell command to prepend to the linter command
    flake8_command_prefix: # optional, default is 
    # Enable or disable Mypy checks
    mypy: # optional
    # Additional arguments to pass to the linter
    mypy_args: # optional, default is 
    # Directory where the Mypy command should be run
    mypy_dir: # optional
    # Extensions of files to check with Mypy
    mypy_extensions: # optional, default is py
    # Shell command to prepend to the linter command
    mypy_command_prefix: # optional, default is 
    # Enable or disable RuboCop checks
    rubocop: # optional
    # Additional arguments to pass to the linter
    rubocop_args: # optional, default is 
    # Directory where the RuboCop command should be run
    rubocop_dir: # optional
    # Extensions of files to check with RuboCop
    rubocop_extensions: # optional, default is rb
    # Shell command to prepend to the linter command
    rubocop_command_prefix: # optional, default is 
    # Enable or disable SwiftFormat checks
    swiftformat: # optional
    # Additional arguments to pass to the linter
    swiftformat_args: # optional, default is 
    # Directory where the SwiftFormat command should be run
    swiftformat_dir: # optional
    # Extensions of files to check with SwiftFormat
    swiftformat_extensions: # optional, default is swift
    # Shell command to prepend to the linter command
    swiftformat_command_prefix: # optional, default is 
    # Enable or disable SwiftFormat checks
    swift_format_lockwood: # optional
    # Additional arguments to pass to the linter
    swift_format_lockwood_args: # optional, default is 
    # Directory where the SwiftFormat command should be run
    swift_format_lockwood_dir: # optional
    # Extensions of files to check with SwiftFormat
    swift_format_lockwood_extensions: # optional, default is swift
    # Shell command to prepend to the linter command
    swift_format_lockwood_command_prefix: # optional, default is 
    # Enable or disable swift-format checks
    swift_format_official: # optional
    # Additional arguments to pass to the linter
    swift_format_official_args: # optional, default is 
    # Directory where the swift-format command should be run
    swift_format_official_dir: # optional
    # Extrensions of files to check with swift-format
    swift_format_official_extensions: # optional, default is swift
    # Shell command to prepend to the linter command
    swift_format_official_command_prefix: # optional, default is 
    # Enable or disable SwiftLint checks
    swiftlint: # optional
    # Additional arguments to pass to the linter
    swiftlint_args: # optional, default is 
    # Directory where the SwiftLint command should be run
    swiftlint_dir: # optional
    # Extensions of files to check with SwiftLint
    swiftlint_extensions: # optional, default is swift
    # Shell command to prepend to the linter command
    swiftlint_command_prefix: # optional, default is 
